---
  hosts: all
  gather_facts: False
  pre_tasks:
  - raw: sudo apt -qy update&& sudo apt install -qy python3&& sudo apt install -qy python&& sudo apt install -qy python-pip&& sudo pip install docker-py
  - setup:

  tasks:
   - name: Install common roles
     role:
      - "{{ docker, become: yes }}"


   - name: Install ELS
     role:
      - "{{ els, become: yes }}"
      
   - name: Install Kibana
     role:
      - "{{ kiban, become: yes }}"
      
   - name: Install Metric
     role:
      - "{{ metricbeat, become: yes }}"
