---
- name: Create Directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/opt/{{ service }}/config"
    - "/opt/{{ service }}/logs"

  - name: Install docker
    apt:
      name: docker.io
      update_cache: yes
      state: present