---

 - name: Pull and started ELS
    docker_image:
        name: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        source: pull
    
  - name: Start ELS
    docker_container:
      name: Els
      image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
      state: started
      environment:discovery.type=single-node
      ports:
        - "9200:9200"
        - "9300:9300"
      volumes:
        - /var/share/elasticsearch:/usr/share/elasticsearch/data