pipeline {
  options {
      timeout(time: 30, unit: 'MINUTES')
    }
    agent none 
    stages {
        stage ('Checkout') {
		    agent {
				label 'master'
			}
            steps {
                script {
                    checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '2bc910d2-09ff-4eec-a53f-d05892b35bc7', url: 'https://github.com/ystroog/devops.git']]])
                    CurrentVersion = sh script:"git tag | sort -r | head -1", returnStdout: true
                    CurrentVersion = CurrentVersion.trim()
                    nextVersion = CurrentVersion + 1
                    commitIDshort = sh script:"git rev-parse HEAD | cut -c1-10", returnStdout: true
                    BuildVersion = "${CurrentVersion}_${commitIDshort}"
                }
            }
        }
        stage ('Unit Test') {
			agent {
				label 'master'
			}
            steps {
                script {
                    dir ('cicd') {
                        try {
                            sh 'python ExperimentTests.py'
                        } catch (err) {
                            println("Unit Test failed for ${BuildVersion}")
                            currentBuild.result = 'UNSTABLE'
                        }
						stash includes: '*', name: 'files', useDefaultExcludes: false
                    }
                }
            }
        }
		stage('build') {
			agent {
				label 'myagent'
			}
			steps {
				dir ('cicd') {	
				unstash 'files'
				sh "docker build . -t  experiment:${BuildVersion}"
				}	
			}

		}
		stage('tag build'){
			agent {
				label 'master'
			}
			steps {
				dir('cicd'){
					node {
					String credentialsId="2bc910d2-09ff-4eec-a53f-d05892b35bc7"
					String gitLogin="ystroog"
					String gitRepo="https://github.com/ystroog/devops.git"
					git credentialsId: "${credentialsId}", url: "${gitRepo}"   
					tagName="My-first tagging"    
					sh(script: "git tag $tagName")
					sshagent([credentialsId])
					sh(script: 'git push --tags')
					}
				}	
			}
		}
	}
}