pipeline {
  options {
      timeout(time: 30, unit: 'MINUTES')
    }
    agent none 
    stages {
        stage('Get ip from user') {
			agent {
				label 'master'
			}
			steps {
				dir ('cicd/'){
				script { 
				targetIP = input(
							id: 'userInput', message: 'ip add',
							parameters: [
								string(defaultValue: '10.0.0.32',
									   description: 'ip address',
									   name: 'IP')])
					}
				}
			}
		}
		stage('Docker installation in the re,ote machine') {
			agent {
				label 'master'
			}
            steps {
				dir ('cicd/'){
					sh 'ls'
					sh 'cat hosts'
					sh "sed -i 's/host_ip/${targetIP}/g' hosts"
					sh 'cat hosts'
					sh "ansible-playbook -i hosts  -u root -b --private-key=/var/jenkins_home/ansible/id_rsa main.yml"
					sh "docker save -o docker-images.tar experiment:${BuildVersion}"
					sh "docker-machine scp ./docker-images.tar ${targetIP}:/"
					sh "ansible-playbook -i hosts  -u root -b --private-key=/var/jenkins_home/ansible/id_rsa main_container.yml"
				}
            }
        }            
	}
}