---

 - name: Pull and started Kibana
    docker_image:
        name: docker.elastic.co/kibana/kibana:6.5.4
        source: pull
        
  - name: Kibana Docker
    docker_container:
      name: Kibana
      hostname: kibana
      image: kibana:6.5.4
      state: started
      environment:
        SERVER_NAME: kibana
        server.host: "0.0.0.0"
        ELASTICSEARCH_HOSTS:  [ "http://localhost:9200" ]
      link: 
      	  - "elasticsearch"
      ports:
        - "5601:5601"
      volumes:
        - /var/elasticsearch:/usr/share/elasticsearch/data
       restart: yes

  
  
  
