---
  
  - name: Pre Install docker 
    raw: yum check-update
      
  - name: Install docker service
    raw: curl -fsSL https://get.docker.com/ | sh
    
  - name: Start docker service
    service:
       name: docker
       state: started