pipeline {
    agent {
        label 'master'
    }
    stages {
        stage('checkout'){
            steps {
                script {
                    cleanWs()
                    git credentialsId: 'ea741a94-9357-426e-aa44-19f7370634c2', url: 'https://github.com/ystroog/devops.git'
                    sh 'ls'
                }
            }
        }
        stage('Ansible Playbook inserting ELasticsearch host') {
            steps {
                dir('Devops/') {
                    script {
                    ElstargetIP = input(
                            id: 'userInput', message: 'Please Input the Elasticsearch ip address',
                            parameters: [
                                string(defaultValue: '0.0.0.0',
                                       description: 'ip address',
                                       name: 'IP')]) 
                    }
                }
            }
        }
        stage('Ansible Playbook inserting Agent host') {
            steps {
                dir('Devops/') {
                    script {
                    AgenttargetIP = input(
                            id: 'userInput', message: 'Please Input the Agent ip address',
                            parameters: [
                                string(defaultValue: '0.0.0.0',
                                       description: 'ip address',
                                       name: 'IP')]) 
                    }
                }
            }
        }
        stage {
            steps {
                sh "sed -i 's/HOST_IP/${targetIP}/g' hosts"
                    sh "sed -i 's/host_ip/${targetIP}/g' group_vars/all"
                    sh 'cat hosts'
                    sh 'cat group_vars/all'
                    sh "ansible-playbook -i hosts  -u ubuntu -b  --private-key=/var/jenkins_home/ansible/my.pem roles/Configure/tasks/main.yml"
                    sh "ansible-playbook -i hosts  -u ubuntu -b  --private-key=/var/jenkins_home/ansible/my.pem playbook.yml"
            }
        }            
    }
}
