pipeline {
    agent {
        label 'master'
    }
    stages {
        stage('checkout'){
            steps {
                script {
                    cleanWs()
                    git credentialsId: 'ea741a94-9357-426e-aa44-19f7370634c2', url: 'https://github.com/ystroog/devops.git'
                    sh 'ls'
                }
            }
        }
        stage('Ansible Playbook inserting host') {
            steps {
                dir ('Devops/') {
                    script {
                    targetIP = input(
                            id: 'userInput', message: 'ip add',
                            parameters: [
                                string(defaultValue: '0.0.0.0',
                                       description: 'ip address',
                                       name: 'IP')]) 
                    }
                }
            }
        }
        script {
        // Show the select input modal
       def INPUT_PARAMS = input message: 'Please Provide Parameters', ok: 'Next',
                        parameters: [
                        choice(name: 'IMAGE_TAG', choices: getDockerImages(), description: 'Available Docker Images')]
        }
    
    }
}
